### ISSUE TITLE
Error: 'fetchExtendedChromInfoFromUCSC' is defunct.

### ISSUE THREAD

**Issue by arslan9732** [your-highness/normR#18] opened 2021-09-20 12:42 UTC
I am using normr version ‘1.18.0’. The `enrichR()` function gave the following error message.
`Error: 'fetchExtendedChromInfoFromUCSC' is defunct.
Use 'getChromInfoFromUCSC' instead.
See help("Defunct")`

**Comment by your-highness** [comment] 2021-09-20 14:58
Thanks for pointing that out! I wonder why this problem was not detected in Bioconductors automatic testing.

The problem is fixed by c084c4b16be3cccd33120912d75eb0a746dda605. Changes are pushed to [Bioconductor devel normR v1.19.2](https://bioconductor.org/packages/devel/bioc/html/normr.html) and [Bioconductor Release 3.13 normR v1.18.1](https://bioconductor.org/packages/release/bioc/html/normr.html) . Please give 1 - 2 days for changes to become available in Bioconductor.

**Closed as completed by your-highness** 2021-09-20 14:58 UTC
